name: Build and Publish to PyPI

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger the workflow for PRs into 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Python
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    # Build the package
    - name: Build the package
      run: |
        python setup.py sdist bdist_wheel

    # Upload to PyPI using Twine
    - name: Upload to PyPI
      env:
        PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        twine upload dist/* -u $PYPI_USERNAME -p $PYPI_TOKEN
